/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type AvailableDTO = {
  available: boolean;
};

export type RegisterTokenEntity = {
  createdAt: string;
  id: string;
  email: string;
};

export type RegistrationBody = {
  tokenId: string;
  firstName: string;
  lastName: string;
  password: string;
  passwordConfirm: string;
};

export type SuccessDTO = {
  success: boolean;
};

export type TokenIdBody = {
  tokenId: string;
};

export type TokenIdPasswordBody = {
  password: string;
  passwordConfirm: string;
  tokenId: string;
};

export type EmailBody = {
  email: string;
};

export type SignupEmailBody = {
  email: string;
  firmId: string;
};
