version: "3.7"
secrets:
  POSTGRES_USER:
    external: true
  POSTGRES_PASSWORD:
    external: true
  POSTGRES_DB:
    external: true
services:
  backend:
    image: distortedlogic/backend:latest
    networks:
      - web
      - backend
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.backend.rule=Host(`backend.memehub.lol`)
        - traefik.http.routers.backend.entrypoints=secure
        - traefik.http.services.backend.loadbalancer.server.port=5000
        - traefik.http.routers.backend.tls.certresolver=letsencrypt
        - traefik.http.services.backend.loadbalancer.sticky.cookie=true
        - traefik.http.services.backend.loadbalancer.sticky.cookie.name=sticky_speed_cow
        - traefik.http.services.backend.loadbalancer.sticky.cookie.httpOnly=true
        # - traefik.http.services.backend.loadbalancer.sticky.cookie.domain=.memehub.lol
        - traefik.http.services.backend.loadbalancer.sticky.cookie.secure=true
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  sitedata:
    image: postgres:latest
    volumes:
      - sitedata:/var/lib/postgresql/data
    networks:
      - backend
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
      POSTGRES_DB_FILE: /run/secrets/POSTGRES_DB
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  redis:
    image: distortedlogic/redis:latest
    volumes:
      - redis:/data
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  controllers:
    image: distortedlogic/controllers:latest
    command: celery worker -B -l info -A controller.CELERY
    networks:
      - backend
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    environment:
      POSTGRES_USER: placeholder
      POSTGRES_PASSWORD: placeholder
      POSTGRES_DB: placeholder
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  notebook:
    image: distortedlogic/notebook:latest
    container_name: notebook
    restart: on-failure
    networks:
      - backend
      - web
    command: jupyter lab
    volumes:
      - ./jupyter/notebooks:/notebooks
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.jupyter.rule=Host(`jupyter.memehub.lol`)
        - traefik.http.routers.jupyter.entrypoints=secure
        - traefik.http.services.jupyter.loadbalancer.server.port=8888
        - traefik.http.routers.jupyter.tls.certresolver=letsencrypt
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: jermeek@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: testtesttest
  #     PGADMIN_ENABLE_TLS: 'True'
  #   labels:
  #     - traefik.enable=true
  #     - traefik.http.routers.pgadmin.rule=Host(`pgadmin.memehub.lol`)
  #     - traefik.http.routers.pgadmin.entrypoints=secure
  #     - traefik.http.services.pgadmin.loadbalancer.server.port=443
  #     - traefik.http.routers.pgadmin.tls.certresolver=letsencrypt
  #   networks:
  #     - web
  #     - backend
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 2
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
volumes:
  sitedata:
  redis:
  # pgadmin:
networks:
  backend:
    driver: overlay
    attachable: true
  web:
    external: true