version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mh_pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redismod:
    container_name: redismod
    image: lobbymatic/redismod:latest
    build:
      context: ./redismod
    entrypoint: '/usr/local/bin/redis-server'
    command: '--include /usr/local/etc/redis/redis.conf --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so'
    volumes:
      - type: bind
        source: ./redismod/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
    ports:
      - '6379:6379'

volumes:
  mh_pg_data:
